---
# ESLint rules
# https://eslint.org/docs/rules/

env:
  browser: true
  es6: true
  node: true

extends:
  # eslint-config-airbnb
  # https://github.com/airbnb/javascript
  - airbnb

  # TypeScript ESLint plugin recommended rules
  # https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/configs/recommended.json
  - plugin:@typescript-eslint/recommended

  # eslint-plugin-import error rules
  # https://github.com/benmosher/eslint-plugin-import/blob/master/config/errors.js
  - plugin:import/errors

  # eslint-plugin-import warning rules
  # https://github.com/benmosher/eslint-plugin-import/blob/master/config/warnings.js
  - plugin:import/warnings

  # eslint-plugin-import typescript rules
  # https://github.com/benmosher/eslint-plugin-import/blob/master/config/typescript.js
  - plugin:import/typescript

  - prettier

globals:
  __DEV__: true

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  project: ./tsconfig.json
  sourceType: module

plugins:
  - '@typescript-eslint'
  - prettier
  - prefer-arrow
  - react
  - react-hooks
  - import

root: true

settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
  react:
    version: detect

rules:
  # eslint official
  arrow-body-style: off
  no-console: warn
  no-param-reassign: off
  no-shadow: off
  no-undef: off
  no-underscore-dangle: off
  no-use-before-define: off
  require-yield: error

  # @typescript-eslint
  '@typescript-eslint/camelcase': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-member-accessibility': off
  '@typescript-eslint/indent': off
  '@typescript-eslint/no-empty-interface': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-namespace': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-shadow': error
  '@typescript-eslint/no-unnecessary-type-assertion': error
  '@typescript-eslint/no-unused-vars':
    - error
    - varsIgnorePattern: '[Rr]eact'
  '@typescript-eslint/no-use-before-define': error

  # prefer-arrow
  prefer-arrow/prefer-arrow-functions:
    - error
    - disallowPrototype: true
      singleReturnOnly: true
      classPropertiesAllowed: false

  # react
  react/jsx-filename-extension:
    - error
    - extensions:
        - jsx
        - tsx

  react/jsx-one-expression-per-line: off
  react/jsx-props-no-spreading: off
  react/jsx-sort-props: error
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
  react/prop-types: off
  react/prefer-stateless-function: off
  react/state-in-constructor: off
  react/destructuring-assignment: off

  # react hooks
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn

  # import
  ## Disable because the importing with the webpack alias is treated as an undeclared module
  import/extensions:
    - off
    - always
    - js: never
      jsx: never
      ts: never
      tsx: never

  import/prefer-default-export: off
  import/no-unresolved: off
  import/order:
    - error
    - groups:
        - internal
        - builtin
        - external
        - parent
        - sibling
        - index
      newlines-between: ignore

  # jsx-a11y
  jsx-a11y/label-has-for: off
  jsx-a11y/label-has-associated-control: off
  jsx-a11y/click-events-have-key-events: off
