# Prettier Options
# https://prettier.io/docs/en/options.html

printWidth: 80
tabWidth: 2
semi: true
singleQuote: true
jsxSingleQuote: false
trailingComma: es5
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: always
proseWrap: preserve
htmlWhitespaceSensitivity: css
endOfLine: auto
